// Generated by https://quicktype.io

export interface User {
  id?:               string;
  name:             string;
  lastName:         string;
  age:              number;
  city:             string;
  birthDate?:        string;
  registrationDate?: string;
  spouseBirthDate?:  string;
  degree?:           string;
  workplace?:        string;
  salary?:           number;
  experienceYears?:  number;
}
